"""Malleable C2 profile generator for Phantom Beacon.

Generates the C++ header `malleable_config.h` from a JSON profile file so
the beacon's network fingerprint is fully customizable: URI paths, user-agent
pool, sleep cadence, headers, and traffic shape parameters.

The engine can also generate `malleable_config.h` from the `--set key=value`
convenience interface on the command line.
"""

import json as _json
import os as _os
import secrets as _secrets
import hashlib as _hashlib
from typing import Optional as _Optional


DEFAULT_PROFILE = {
    "get_paths": [
        "/api/v1/ping",
        "/api/v1/status",
        "/js/jquery-3.6.0.min.js",
        "/static/css/bootstrap.min.css",
        "/favicon.ico",
    ],
    "post_paths": [
        "/api/v1/result",
        "/login.php",
        "/upload.aspx",
        "/api/v1/submit",
    ],
    "decoy_paths": [
        "/index.html",
        "/assets/logo.png",
        "/static/js/app.js",
        "/api/v1/config",
        "/health",
    ],
    "user_agents": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    ],
    "extra_headers": [
        "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language: en-US,en;q=0.9",
        "Cache-Control: no-cache",
    ],
    "sleep_ms": 5000,
    "jitter": 30,
    "randomize_uri_casing": True,
    "prepend_slash": True,
}


# ────────────────────────────────────────────────────────────────────────────
#  Load / Save
# ────────────────────────────────────────────────────────────────────────────

def load_profile(path: str) -> dict:
    """Load a JSON malleable profile file, filling missing keys from defaults."""
    with open(path, "r", encoding="utf-8") as f:
        user = _json.load(f)

    merged = dict(DEFAULT_PROFILE)
    merged.update(user)

    # validate types
    for key in ("get_paths", "post_paths", "decoy_paths", "user_agents", "extra_headers"):
        if not isinstance(merged.get(key), list):
            merged[key] = DEFAULT_PROFILE[key]
    for key in ("sleep_ms", "jitter"):
        if not isinstance(merged.get(key), int):
            merged[key] = DEFAULT_PROFILE[key]
    for key in ("randomize_uri_casing", "prepend_slash"):
        if not isinstance(merged.get(key), bool):
            merged[key] = DEFAULT_PROFILE[key]

    merged["sleep_ms"] = max(1000, merged["sleep_ms"])
    merged["jitter"] = min(100, max(0, merged["jitter"]))
    return merged


def save_default_profile(path: str) -> str:
    """Write the default malleable profile to *path* (useful as a template)."""
    _os.makedirs(_os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        _json.dump(DEFAULT_PROFILE, f, indent=2)
    return path


# ────────────────────────────────────────────────────────────────────────────
#  C++ code generation
# ────────────────────────────────────────────────────────────────────────────

def _cpp_string_list(name: str, values: "list[str]") -> str:
    lines = []
    lines.append(f"static const std::vector<std::string> {name} = {{")
    for v in values:
        escaped = v.replace("\\", "\\\\").replace("\"", "\\\"")
        lines.append(f'    "{escaped}",')
    lines.append("};")
    return "\n".join(lines)


def generate_malleable_header(profile: dict, out_path: _Optional[str] = None) -> str:
    """Generate malleable_config.h from a profile dict.

    Returns the content as a string. If *out_path* is given, also writes it.
    """
    lines = [
        "#pragma once",
        "// Auto-generated by phantom.utils.malleable — do not edit manually.",
        "// Malleable C2 profile — controls all observable beacon network behaviour.",
        "",
        "#include <string>",
        "#include <vector>",
        "",
        "#define MALLEABLE_PROFILE_DEFINED",
        "",
    ]

    # generate profile function
    lines.append("inline malleable::Profile malleable_build_profile() {")
    lines.append("    malleable::Profile p;")

    for list_key in ("get_paths", "post_paths", "decoy_paths", "user_agents", "extra_headers"):
        cpp_name = list_key + "_"
        lines.append(_cpp_string_list(cpp_name, profile[list_key]))
        lines.append(f"    p.{list_key} = {cpp_name};")

    lines.append(f"    p.sleep_ms = {profile['sleep_ms']};")
    lines.append(f"    p.jitter = {profile['jitter']};")
    lines.append(f"    p.randomize_uri_casing = {'true' if profile['randomize_uri_casing'] else 'false'};")
    lines.append(f"    p.prepend_slash = {'true' if profile['prepend_slash'] else 'false'};")
    lines.append("    return p;")
    lines.append("}")

    content = "\n".join(lines) + "\n"

    if out_path:
        _os.makedirs(_os.path.dirname(out_path) or ".", exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    return content


# ────────────────────────────────────────────────────────────────────────────
#  builder integration
# ────────────────────────────────────────────────────────────────────────────

def write_malleable_config(beacon_dir: str,
                           profile_path: _Optional[str] = None) -> str:
    """Entrypoint used by builder.py. Generates malleable_config.h.

    - If *profile_path* is given, loads that JSON profile.
    - Otherwise generates from defaults.
    - Writes `malleable_config.h` to beacon_dir/src/.
    - Returns the written path.
    """
    src_dir = _os.path.join(beacon_dir, "src")
    _os.makedirs(src_dir, exist_ok=True)
    out_path = _os.path.join(src_dir, "malleable_config.h")

    profile = load_profile(profile_path) if profile_path else dict(DEFAULT_PROFILE)
    generate_malleable_header(profile, out_path)
    return out_path


# ────────────────────────────────────────────────────────────────────────────
#  CLI handler (shared between core shell and C2 shell)
# ────────────────────────────────────────────────────────────────────────────

def handle_malleable_command(arg: str) -> None:
    """Handle `malleable [show|save|load|recommend]` for both shell contexts.

    Call this from do_malleable() in both core/shell.py and core/c2_shell.py.
    """
    from phantom.utils.notifier import notifier
    from rich.console import Console
    from rich.table import Table
    from rich.panel import Panel
    console = Console()

    parts = arg.strip().split()
    action = parts[0].lower() if parts else "show"

    if action in ("save", "save-default", "dump"):
        target = parts[1] if len(parts) > 1 else _os.path.join("data", "malleable_profile.json")
        path = save_default_profile(target)
        notifier.success(f"Default malleable profile saved to {path}")
        notifier.info("Edit the URIs/user-agents/headers in this file, then rebuild with:")
        notifier.info(f"  generate <platform> --profile {path}")
        return

    if action in ("recommend", "advise", "suggest"):
        from phantom.utils.profile_advisor import get_advisor
        from phantom.core.session import session
        advisor = get_advisor()

        os_hint = ""
        services = []
        target_ip = session.target or ""

        scan_res = session.get_result("scan") or {}
        scan_text = str(scan_res).lower()

        if "windows" in scan_text:
            os_hint = "windows"
        elif "linux" in scan_text or "unix" in scan_text:
            os_hint = "linux"
        elif "mac" in scan_text or "darwin" in scan_text:
            os_hint = "macos"
        elif "android" in scan_text:
            os_hint = "android"

        svc_indicators = [
            "iis", "apache", "nginx", "tomcat", "exchange",
            "sharepoint", "wordpress", "django", "flask",
            "spring", "node", "express", "mysql", "postgresql",
            "mssql", "redis", "mongodb", "smtp", "ftp", "ssh"
        ]
        for svc in svc_indicators:
            if svc in scan_text:
                services.append(svc)

        risk = session.mode or "default"
        if "stealth" in risk.lower():
            risk = "stealth"
        elif "aggressive" in risk.lower():
            risk = "aggressive"

        recs = advisor.recommend(
            os_hint=os_hint,
            services=services or None,
            risk_level=risk,
            target_ip=target_ip,
            limit=3,
        )

        table = Table(title="[bold]Recommended Malleable Profiles[/]", border_style="magenta")
        table.add_column("Rank", style="cyan", width=4)
        table.add_column("Family", style="magenta")
        table.add_column("Score", style="green", width=6)
        table.add_column("Reasoning", style="white", width=40)

        for i, rec in enumerate(recs, 1):
            table.add_row(str(i), rec.recipe.family, f"{rec.score:.0f}", rec.reasoning)

        console.print(table)

        if recs:
            best = recs[0]
            console.print(Panel.fit(
                f"[bold green]Best: {best.recipe.family}[/] -- {best.recipe.description}\n"
                f"Save with: [bold]malleable save[/] then rebuild with [bold]generate --profile[/]",
                border_style="green"))
        else:
            notifier.warn("No target data available. Run a scan first, then retry.")
        return

    if action in ("load", "view", "show"):
        target = parts[1] if len(parts) > 1 else None
        profile = load_profile(target) if target and _os.path.exists(target) else DEFAULT_PROFILE

        table = Table(title="[bold]Malleable C2 Profile[/]", border_style="magenta")
        table.add_column("Setting", style="cyan")
        table.add_column("Value", style="white")
        table.add_row("GET paths", str(profile.get("get_paths", [])))
        table.add_row("POST paths", str(profile.get("post_paths", [])))
        table.add_row("Decoy paths", str(profile.get("decoy_paths", [])))
        table.add_row("User-Agents", f"{len(profile.get('user_agents', []))} entries")
        table.add_row("Extra Headers", f"{len(profile.get('extra_headers', []))} entries")
        table.add_row("Sleep (ms)", str(profile.get("sleep_ms", 5000)))
        table.add_row("Jitter (%)", str(profile.get("jitter", 30)))
        table.add_row("URI casing random", str(profile.get("randomize_uri_casing", True)))
        console.print(table)
        return

    notifier.info("Usage: malleable [show|save|recommend]")
    notifier.info("  save      - write default profile to data/malleable_profile.json")
    notifier.info("  show      - display current profile settings")
    notifier.info("  recommend - suggest profile based on target (auto-detects from scan)")
    notifier.info("Then rebuild: generate <platform> --profile data/malleable_profile.json")